### ISSUE TITLE
Cleanup repository and target framework.

### ISSUE THREAD

**Issue by tacosontitan** [tacosontitan/Glitter#44]
### 🐛 Category

😖 Other

### 🔢 Version

🐣 Pre-Release

### 📝 What needs to be done?
- [x] Reorganize the file structure.
  - [x] Move solution file.
  - [x] [Separate samples from core functionality.](https://github.com/tacosontitan/Glitter/issues/42)
    - [x] Create `samples` folder at repository root.
    - [x] Move `Freya` to the newly created `samples` folder.
    - [x] Update project references.
  - [x] [Separate tests from core functionality.](https://github.com/tacosontitan/Glitter/issues/43)
    - [x] Create `tests` folder at repository root.
    - [x] Move `Glitter.Tests` to the newly created `tests` folder.
    - [x] Update project references.
- [x] [Update target framework from .NET 6 to .NET 7.](https://github.com/tacosontitan/Glitter/issues/41)
  - [x] Glitter
  - [x] Glitter.Discord
  - [x] Glitter.Commands.OpenSource
  - [x] Glitter.Tests
  - [x] Freya
- [ ] [Change `UseGlitter` to `AddGlitter`.](https://github.com/tacosontitan/Glitter/issues/39)
